name:                tokonoma
version:             0.1.0.0
github:              "eatslowthinkquick/tokonoma"
license:             BSD3
author:              "Ruben Lie King"
maintainer:          "hello@rubenlieking.com"
copyright:           "2018 Ruben Lie King"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/githubuser/tokonoma#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - directory
  - http-client
  - http-client-tls
  - servant
  - servant-server
  - servant-auth
  - text
  - wai
  - wai-extra
  - warp

library:
  source-dirs: src/haskell
  exposed-modules:
    Main

executables:
  tokonoma:
    main: Main.hs
    source-dirs: src/haskell
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - tokonoma

tests:
  tokonoma-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - tokonoma
